<?php
/**
 * @file
 *
 */

include_once('theme/cross_manage.theme.inc');

/**
 * Implements hook_menu().
 */
function cross_manage_menu() {
  $items = array();

  $items['crossing-block'] = array(
    'title' => 'Crossing Block Management',
    'description' => 'Manage your Breeding Program.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cross_manage_set_crossing_block_form'),
    'access arguments' => array('administer tripal'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['crossing-block/%/%/%/summary'] = array(
    'title' => 'Crossing Block Management',
    'description' => 'Manage your Breeding Program.',
    'page callback' => 'cross_manage_workflow_page',
    'page arguments' => array(FALSE, 1, 2, 3),
    'access arguments' => array('administer tripal'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Planning Stages
  $items['crossing-block/%/%/%/set-crosses'] = array(
    'title' => 'Plan Crosses',
    'description' => 'A form to set the crosses to be made for a given crossing block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cross_manage_crossingblock_set_cross_parents_form',1,2,3),
    'file' => 'includes/step1_forms.inc',
    'access arguments' => array('administer tripal'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['crossing-block/%/%/%/set-crosses/parents'] = array(
    'title' => 'Parents',
    'description' => 'A form to set the crosses to be made for a given crossing block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cross_manage_crossingblock_set_cross_parents_form',1,2,3),
    'file' => 'includes/step1_forms.inc',
    'access arguments' => array('administer tripal'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );

  $items['crossing-block/%/%/%/set-crosses/F1s'] = array(
    'title' => 'F1\'s',
    'description' => 'A form to set the crosses to be made for a given crossing block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cross_manage_crossingblock_set_cross_f1s_form',1,2,3),
    'file' => 'includes/step1_forms.inc',
    'access arguments' => array('administer tripal'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -8
  );

/**
  $items['crossing-block/%/%/%/set-crosses/marker-data'] = array(
    'title' => 'Marker Data',
    'description' => 'A form to set the crosses to be made for a given crossing block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cross_manage_crossingblock_set_marker_data_form',1,2,3),
    'file' => 'includes/step2_forms.inc',
    'access arguments' => array('administer tripal'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -6
  );
*/

  // Report Data
  $items['crossing-block/%/%/%/report-crosses'] = array(
    'title' => 'Report Cross Outcome',
    'description' => 'A form to set the crosses to be made for a given crossing block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cross_manage_crossingblock_assign_cross_num_form',1,2,3),
    'file' => 'includes/step4_forms.inc',
    'access arguments' => array('administer tripal'),
    'type' => MENU_CALLBACK,
    'weight' => -6
  );

  // CALLBACKS:
  // Autocomplete stock name (no id).
  // tripal_ajax/cross_manage/stock_name/GENUS
  $items['tripal_ajax/cross_manage/stock_name/%'] = array(
    'page callback' => 'cross_manage_stock_name_autocomplete',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implements hook_theme().
 */
function cross_manage_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['cross_manage_workflow'] = array(
    'template' => 'cross_manage_workflow',
    'path' => "$path/theme/templates",
  );

  $items['cross_manage_crossingblock_parents'] = array(
    'render element' => 'element',
    'function' => 'theme_cross_manage_crossingblock_parents'
  );

  $items['cross_manage_crossingblock_f1'] = array(
    'render element' => 'element',
    'function' => 'theme_cross_manage_crossingblock_f1'
  );

  $items['cross_manage_crossingblock_f1_joyride'] = array(
    'template' => 'crossingblock_f1_joyride',
    'path' => "$path/theme/templates",
  );

  $items['cross_manage_shepherd_start_tour_link'] = array(
    'function' => 'theme_cross_manage_shepherd_start_tour_link',
  );

  $items['cross_manage_crossingblock_marker_entry'] = array(
    'render element' => 'element',
    'function' => 'theme_cross_manage_crossingblock_marker_entry'
  );

  return $items;
}

/**
 * @file
 * Forms for managing a breeding program.
 */

/**
 * Workflow page.
 */
function cross_manage_workflow_page($is_launchpad = FALSE, $cb_species = NULL, $cb_year = NULL, $cb_season = NULL) {

  return theme(
    'cross_manage_workflow',
    array(
      'is_launchpad' => $is_launchpad,
      'crossingblock_species' => $cb_species,
      'crossingblock_year' => $cb_year,
      'crossingblock_season' => $cb_season
    )
  );
}

/**
 * Alter Crossing Block form pages to remove the sidebars for more focussed data entry
 */
function cross_manage_page_alter(&$page) {

  // If this page is:
  //   1) The path is crossing-block/*
  //   2) It's a form
  if (preg_match('%crossing-block/%',current_path())) {
    if (isset($page['content']['system_main']['#form_id'])) {
      unset($page['sidebar_second']);
    }
  }
}

/**
 * Set the crossing block
 *
 * This form sets the crossing block and then re-directs to the specified
 * crossing block management form
 *
 * Found in $form_state['build_info']['args']:
 * @param 0
 *   The path of the form to redirect to
 */
function cross_manage_set_crossing_block_form($form, $form_state) {

  $form['#attached']['js'] = array(
    drupal_get_path('module', 'cross_manage') . '/theme/js/workflow_diagram.js',
    'http://d3js.org/d3.v3.min.js'
  );

  $form['#attached']['css'][] = array(
    'type' => 'inline',
    'data' => '
      #crossmanage-crossing-block-diagram {
        float: left;
        width: 500px;
        margin-right: 50px;
        margin-top: -30px;
        margin-bottom: 25px;
      }
      #crossmanage-crossing-block-form.full fieldset{
        margin-top: 50px;
      }
    '
  );

  $form['diagram'] = array(
    '#type' => 'markup',
    '#markup' => '<div id="crossmanage-crossing-block-diagram" class="full">
  <div id="crossmanage-intro-stages-diagram"></div>
  <strong>Figure: Representation of the steps involved in managing a crossing block.</strong>
</div>'
  );

  $form['form'] = array(
    '#type' => 'fieldset',
    '#title' => 'Select Crossing Block',
    '#description' => 'Please select the date and crop of the crossing block you are interested in.',
    '#prefix' => '<div id="crossmanage-crossing-block-form" class="full">',
    '#suffix' => '</div>'
  );

  // @TODO: Add administrative form allowing selection of crops to show here.
  $crops = array(
    'Cicer' => 'Chickpea',
    'Phaseolus' => 'Common Bean',
    'Lens' => 'Lentil',
    'Pisum' => 'Field Pea'
  );
  $form['form']['crop'] = array(
    '#type' => 'select',
    '#title' => 'Crop',
    '#options' => $crops,
    '#description' => 'The species of the germplasm you are crossing.'
  );

  // @TODO: allow admin to set first year of breeding program.
  $program_start_year = 2000;
  $years = range($program_start_year, date('Y')+2);
  $years = array_combine($years, $years);
  $form['form']['year'] = array(
    '#type' => 'select',
    '#title' => 'Year',
    '#options' => $years,
    '#default_value' => date('Y'),
    '#description' => 'The year the crosses were or are to be made in.'
  );

  $seasons = array('Spring', 'Summer', 'Fall', 'Winter');
  $seasons = array_combine($seasons, $seasons);
  $form['form']['season'] = array(
    '#type' => 'select',
    '#title' => 'Season',
    '#options' => $seasons,
    '#description' => 'The season the crosses were made in.'
  );

  $form['form']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Crossing Block Summary',
  );

  return $form;
}

/**
 * Submit for cross_manage_crossingblock_set_crossing_block_form()
 */
function cross_manage_set_crossing_block_form_submit($form, &$form_state) {

    $species = str_replace(' ','-',$form_state['values']['crop']);
    $year = $form_state['values']['year'];
    $season = $form_state['values']['season'];

    $form_state['rebuild'] = FALSE;
    $form_state['redirect'] = format_string(
      'crossing-block/@species/@year/@season/summary',
      array(
        '@species' => str_replace(' ','-',$form_state['values']['crop']),
        '@year' => $form_state['values']['year'],
        '@season' => $form_state['values']['season'],
      )
    );

}

/**
 * Implements hook_libraries_info().
 */
function cross_manage_libraries_info() {

  $libraries['joyride'] = array(
    'name' => 'Joyride Site Tour',
    'vendor url' => 'http://zurb.com/playground/jquery-joyride-feature-tour-plugin',
    'download url' => 'https://github.com/zurb/joyride/archive/master.zip',
    'version' => '2.1',
    'files' => array(
        'js' => array('jquery.joyride-2.1.js'),
        'css' => array('joyride-2.1.css'),
    ),
  );

  $libraries['shepherd'] = array(
    'name' => 'Shepherd Site Tour',
    'vendor url' => 'http://github.hubspot.com/shepherd/docs/welcome/',
    'download url' => 'https://github.com/HubSpot/Shepherd',
    'version' => '0.7',
    'files' => array(
        'js' => array('shepherd.js'),
        'css' => array(
          'css/shepherd-theme-arrows.css'
        ),
    ),
  );

  return $libraries;
}

/**
 * Custom sort function: Sort cross management parents numerically.
 *
 * NOTE: Cannot use regular numeric sort because the parent number is stored
 * as a string to allow use of A, B, C, etc.
 * NOTE: Cannot use natsort() because the parents array is an array of objects.
 */
function cross_manage_sort_parents_by_pnumber($a, $b) {
  return strnatcasecmp($a->parent_number, $b->parent_number);
}

/**
 * Custom Callback: Keep elements with a value greater than 2.
 * @see array_filter().
 */
function cross_manage_filter_keep_2plus($val, $key) {
  return ($val >= 2) ? TRUE : FALSE;
}

/**
 * Format Number: Add ordinal suffix (ie: 3rd).
 */
function cross_manage_format_number_ordinal($number) {

  $ends = array('th','st','nd','rd','th','th','th','th','th','th');
  if ((($number % 100) >= 11) && (($number%100) <= 13)) {
    return $number. 'th';
  }
  else {
    return $number. $ends[$number % 10];
  }

}

/**
 * Retrieve the stock_id based on the name.
 * Supported name locations include stock.name, stock.uniquename.
 */
function cross_manage_get_stock_by_name($name, $genus) {

  $result = chado_query('
    SELECT stock_id
    FROM {stock} s
    LEFT JOIN {organism} o ON o.organism_id=s.organism_id
    WHERE (s.name=:name OR s.uniquename=:name)
      AND o.genus=:genus',
    array(':name' => $name, ':genus' => $genus))->fetchAll();

  if (sizeof($result) == 1) {
    return $result[0]->stock_id;
  }
  return $result;
}

/**
 * FORM AUTOCOMPLETE: Return stock name (no id).
 */
function cross_manage_stock_name_autocomplete($genus, $string) {
  $matches = array();

  $results = chado_query('
    SELECT s.name
    FROM {stock} s
    LEFT JOIN {organism} o ON o.organism_id=s.organism_id
    WHERE s.name~:string AND o.genus=:genus
    ORDER BY char_length(s.name) ASC, s.name ASC
    LIMIT 10',
    array(':genus' => $genus, ':string' => $string)
  );
  foreach ($results as $r) {
    $matches[$r->name] = $r->name;
  }

  drupal_json_output($matches);
}